name: bakecode

description: >-
  Want to develop flows that run in a BakeCode Ecosystem? This
  package provides the framework to build awesome flows that 
  can run and interact in a BakeCode Ecosystem.

version: 0.1.0-alpha

homepage: https://github.com/crysalisdevs/bakecode-jobs.git

publish_to: "none"

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  meta: ^1.2.4
